# Generated by Django 5.0.1 on 2024-01-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Citys',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Countrys',
        ),
        migrations.RenameModel(
            old_name='Marks',
            new_name='Markss',
        ),
        migrations.RenameModel(
            old_name='Subject1',
            new_name='Subject1s',
        ),
    ]
